### ISSUE TITLE
error on import due to cligj dependency

### ISSUE THREAD

**Issue by jgerardsimcock** [perrygeo/python-rasterstats#145]
I am trying to import the module and I get the following error:

`` 15 @click.command(context_settings=SETTINGS)``
``---> 16 @cligj.features_in_arg``
`` 17 @click.version_option(version=version, message='%(version)s')``
``18 @click.option('--raster', '-r', required=True)``

`AttributeError: 'module' object has no attribute 'features_in_arg'`

I am working with rasterstats version 0.12.0. I've looked at cligj and there definitely is a method called `features_in_arg`.

**Comment by jgerardsimcock** [comment]
I needed to update other dependencies.

**Comment by tnigon** [comment]
Do you know which dependencies you had to update? I am having this same issue.

**Comment by ckrapu** [comment]
I'm having the same issue. Any update?

**Comment by perrygeo** [comment]
You need to `pip install -U 'cligj>=0.4'` as per the project requirements.

**Comment by ckrapu** [comment]
Got it. Thanks!
